self:
  no_async: true
  compatibility:
    from: 0.1470294456

ffmpeg:
  bin: /usr/bin/ffmpeg
  threads: 0

profile:

  scene_detector:
    is_abstract: true           # Dummy profile (only for inheritance)
    format: null                #   without format.
    #source: ./out/d-1-30.mp4   # Path to source file of device
    video:                      # Video settings
      codec: null               #   without any codec
      showinfo: true            #   but with showinfo filter
      scene:                    #   and scene (shot) detection
        threshold: 0.1          #     that have threshold ~= 0.1.
    audio: null                 # There is no any audio settings.
    output:                     # Output settings
      file_name: qq             #   There is no any output file.
    log:                        # But it has log that is
      callback: frame_info      #   handled with specific callback
      dir_name: ./out           #   and written  to `./out` dir.

  scene_04:                       # Conrete «Soft» profile
    extends: scene_detector       #   that extends `scene_detector`.
    video_scene_threshold: 0.4    #   and sets threshold

  scene_04:                       # Conrete «Hard» profile
    extends: scene_detector       #   that extends `scene_detector`.
    video_scene_threshold: 0.4    #   and sets threshold