self:
  no_async: true
  compatibility:
    from: 0.1505573195

ffmpeg:
  bin: /usr/bin/ffmpeg
  threads: 0

profile:

  base:
    # you can mark profile as is_abstract
    # and it will be used only for inheritance.
    is_abstract: true
    output:
      dir_name: /tmp
    source: input/files/are/from/config
    
  ## Semi-TVzavr's profile for HDTV devices.
  ## Check in the player on the https://www.tvzavr.ru/
  mai_vob_h264_crf_1080p_hd:
    # Other options are inherited from `base`
    extends: base
    passes: 1
    video:
      width:   -1  # 1920 # for 16:9
      height:  1080
      rate_factor: 23
      framerate: 25       #     Set framerate to 25.
      codec:
        name : h264
        level: 4.2
        preset: veryslow
        profile: high
        weightp: smart
        bframes: 3
        opts:
          keyint: 96
          min_keyint: 96
          no_scenecut: true
        gop:
          closed: true      #       Closed GOP
          no_scenecut: true #       Disable scenecut detecting
        use_cabac: true     #     CABAC (default entropy encoder)
      progressive: true     # Progressive scan (no interlacing).
      pixel_format: yuv420p # Chroma subsampling: 4:2:0
    audio:
      codec:
        name: aac
      channels:  5.1      #   Channels: Stereo or Stereo + 5.1
      bitrate: 128k       #   Recommended for 5.1


  ## Semi-TVzavr's profile for Desctop PAL-like Web Video.
  ## Check in the player on the https://www.tvzavr.ru/
  mai_vob_h264_crf_0720p_hd:
    extends: mai_vob_h264_crf_1080p_hd
    video:
      codec:
        level: 3.1
      width:   -1  # 1280 # for 16:9
      height:  720
      level: 3.1

  ## Semi-TVzavr's profile for Desctop PAL-like Web Video.
  ## Check in the player on the https://www.tvzavr.ru/
  mai_vob_h264_crf_0576p_hi:
    extends: mai_vob_h264_crf_0720p_hd
    video:
      width:  -1  # 1024 # for 16:9
      height: 576 # SD
      codec:
        profile: main
        level: 3.0
    audio:
      channels: stereo
      bitrate: 196k

  ## Semi-TVzavr's profile for Desctop NTSC and VGA-like Web Video.
  ## Check in the player on the https://www.tvzavr.ru/
  mai_vob_h264_crf_0480p_hi:
    extends: mai_vob_h264_crf_0576p_hi
    video:
      width:   -2  # 854 # for 16:9
      height:  480
