ffmpeg:
    bin: /usr/bin/ffmpeg
    threads: 0

profile:
    #high:
        #passes: 1
        #video:
            #width: 1280
            #height:  720
            #bitrate: 2000k
            #preset: veryfast
            #codec:
                #name : libx264
                #profile: high
                #level: 3.1
                #opts: "keyint=96:min-keyint=96:no-scenecut"
                #weightp: 2
                #b-frames: 3

        #audio:
            #channels: 5.1
            #bitrate: 320k
            #volume: 4
            #codec:
                #name: aac
    tvzavr_low2:
        passes: 2
        video:
            width: 480
            height:  270
            bitrate: 250k
            preset: veryfast
            codec:
                name : libx264
                profile: baseline
                level: 3.0
                weightp: 2
                bframes: 3 # -bf
                opts: "keyint=96:min-keyint=96:no-scenecut"
        audio:
            channels: mono
            bitrate: 64k
            volume: 4
            codec:
                name: aac







