ffmpeg:
    bin: /usr/bin/ffmpeg
    threads: 0
    time: 10
profile:
    high:
        suffix: high
        passes: 2
        video:
            width: 1280
            height:  720
            bitrate: 2000k
            preset: ultrafast
            codec:
                name : libx264
                profile: high
                level: 3.1
            pass1:
                params: -weightp 2 -bf 3
        audio:
            channels: 5.1
            bitrate: 320k
            volume: 4
            codec:
                name: aac









