ffmpeg:
  bin: /usr/bin/ffmpeg
  threads: 0

profile:

  base:
    # you can mark profile as is_abstract
    # and it will be used only for inheritance.
    is_abstract: true
    output_dir_name: ./out
    ignore:
      start: 00:00:00
      stop: 00:00:30
      duration:  00:00:30
      source: /home/w495/Videos/input/00003.MTS

  tvzavr_x1:
    is_abstract: true
    passes: 1

  ## Semi-TVzavr's profile for HDTV devices.
  ## Check in the player on the https://www.tvzavr.ru/
  tvzavr_h264_x2_1080p_hd:
    # Other options are inherited from `base`
    extends: base
    is_abstract: true
    passes: 2
    video:
      width:   -1  # 1920 # for 16:9
      height:  1080
      codec:
        name : h264
        preset: veryslow
        profile: high
        weightp: smart
        bframes: 3
        opts: "keyint=96:min-keyint=96:no-scenecut"
        level: 3.1
    audio:
      codec:
        name: aac
      channels: 5.1
      bitrate: 320k

  ## Semi-TVzavr's profile for Desctop PAL-like Web Video.
  ## Check in the player on the https://www.tvzavr.ru/
  tvzavr_h264_x2_0720p_hd:
    extends: tvzavr_h264_x2_1080p_hd
    is_abstract: true
    video:
      width:   -1  # 1280 # for 16:9
      height:  720
      bitrate: 2000k

  ## Semi-TVzavr's profile for Desctop PAL-like Web Video.
  ## Check in the player on the https://www.tvzavr.ru/
  tvzavr_h264_x2_0576p_hi:
    extends: tvzavr_h264_x2_0720p_hd
    is_abstract: true
    video:
      width:  -1  # 1024 # for 16:9
      height: 576 # SD
      bitrate: 1000k
      codec:
        profile: main
        level: 3.0
    audio:
      channels: stereo
      bitrate: 196k

  ## Semi-TVzavr's profile for Desctop NTSC and VGA-like Web Video.
  ## Check in the player on the https://www.tvzavr.ru/
  tvzavr_h264_x2_0480p_hi:
    extends: tvzavr_h264_x2_0576p_hi
    is_abstract: true
    video:
      width:   -1 # 854 # for 16:9
      height:  480

  ## Semi-TVzavr's profile for tablets.
  ## Check in the player on the https://www.tvzavr.ru/
  tvzavr_h264_x2_0360p_nr:
    extends: tvzavr_h264_x2_0480p_hi
    is_abstract: true
    video:
      width:   -1 # 640 # for 16:9
      height:  360
      bitrate: 600k
    audio:
      channels: stereo
      bitrate: 128k

  ## Semi-TVzavr's profile for old mobile devices
  ## Check in the player on the https://www.tvzavr.ru/.
  tvzavr_h264_x2_0270p_lw:
    extends: tvzavr_h264_x2_0360p_nr
    is_abstract: true
    video:
      width:   -1 # 480 # for 16:9
      height:  270
      bitrate: 250k
      codec:
        profile: baseline
    audio:
      channels: mono
      bitrate: 64k

  ## Semi-TVzavr's casted profile for old mobile devices
  tvzavr_h264_x2_0240p_lw:
    extends: tvzavr_h264_x2_0270p_lw
    is_abstract: true
    video:
      width:   -1
      height:  240
      bitrate: 200k

  ## Semi-TVzavr's profile for small devices
  tvzavr_h264_x2_0120p_lw:
    extends: tvzavr_h264_x2_0240p_lw
    depends_on: tvzavr_h264_x2_0120p_pre
    video:
      width:   -1
      height:  120
      bitrate: 100k
    audio:
      bitrate: 32k

  ## Semi-TVzavr's profile for small devices
  tvzavr_h264_x2_0120p_pre:
    extends: tvzavr_h264_x2_0240p_lw
    video:
      width:   -1
      height:  120
      bitrate: 100k
    audio:
      bitrate: 32k


#
#  # High-quality SD video for archive/storage
#  # (PAL at 1Mbit/s in high profile):
#  # from https://www.virag.si/2012/01/web-video-encoding-tutorial-with-ffmpeg-0-9/
#  virag_h264_x1_pal_sd:
#    # Other options are inherited from `base`
#    extends:   base
#    passes: 1
#    video:
#      width:  -1  # 1024 # for 16:9
#      height: 576 # SD
#      codec:
#        preset: slower
#        name : h264
#        profile: high
#      bitrate: 1000k
#    audio:
#      codec:
#        name: aac
#      channels: 5.1
#      bitrate: 196k
#
#  # Standard web video (0480p at 500kbit/s)
#  # from https://www.virag.si/2012/01/web-video-encoding-tutorial-with-ffmpeg-0-9/
#  virag_h264_x1_0480p_web:
#    extends: virag_h264_x1_pal_sd
#    video:
#      height: 480
#      codec:
#        preset: slow
#      bitrate: 500k
#      maxrate: 500k
#      bufsize: 1000k
#    audio:
#      bitrate: 128k
#      channels: stereo
#
#  # 0480p video for iPads and tablets
#  # 0480p at 400kbit/s in main profile
#  # from https://www.virag.si/2012/01/web-video-encoding-tutorial-with-ffmpeg-0-9/
#  virag_h264_x1_0480p_tablet:
#    extends: virag_h264_x1_0480p_web
#    video:
#      codec:
#        profile: main
#      bitrate: 400k
#      maxrate: 400k
#      bufsize: 800k
#
#  # 0360p video for older mobile phones
#  # (0360p at 250kbit/s in baseline profile)
#  # from https://www.virag.si/2012/01/web-video-encoding-tutorial-with-ffmpeg-0-9/
#  virag_h264_x1_0360p_mobile:
#    extends: virag_h264_x1_0480p_tablet
#    video:
#      height: 360
#      codec:
#        profile: baseline
#      bitrate: 250k
#      maxrate: 250k
#      bufsize: 500k
#    audio:
#      bitrate: 96k
#      channels: mono
#
#   0360p video for older mobile phones
#   (0360p at 250kbit/s in baseline profile)
#   from https://www.virag.si/2012/01/webm-web-video-encoding-tutorial-with-ffmpeg-0-9/
#  virag_webm_x1_pal_sd:
#    # Other options are inherited from `base`
#    extends:   base
#    passes: 1
#    format: webm
#    extention: mp4
#    video:
#      width:  -1  # 1024 # for 16:9
#      height: 576 # SD
#      codec:
#        name: vp9
#        quality: good
#        qmin: 10
#        qmax: 42
#      bitrate: 1200k
#      maxrate: 1200k
#      bufsize: 2400k
#    audio:
#      codec:
#        name: libvorbis
#      channels: 5.1
#      bitrate: 196k
#
#  exp_h263_x1_pal_sd:
#    # Other options are inherited from `base`
#    extends:   base
#    passes: 1
#    format: flv
#    extention: flv
#    video:
#      width:  -1  # 1024 # for 16:9
#      height: 576 # SD
#      preset: slower
#      codec:
#        name: flv
#      bitrate: 1200k
#      maxrate: 1200k
#      bufsize: 2400k
#    audio:
#      codec:
#        name: mp3
#      # For flv with mp3 — (44100, 22050, 11025)
#      framerate: 22050
#      channels: mono
#      bitrate: 64k
#
#  exp_10:
#    is_complex: 1
#    exp_dirac_x1_pal_sd:
#      # Other options are inherited from `base`
#      extends:   base
#      passes: 1
#      format: mov
#      video:
#        width:  -1  # 1024 # for 16:9
#        height: 576 # SD
#        codec:
#          name: dirac
#          qscale: 0
#      audio:
#        codec:
#          name: aac
#        channels: mono
#        bitrate: 64k

#  exp_hevc_x1_pal_gray_sd:
#    # Other options are inherited from `base`
#    extends:   base
#    passes: 1
#    format: mp4
#    video:
#      width:  -1  # 1024 # for 16:9
#      height: 576 # SD
#      codec:
#        name: hevc
#        preset: veryslow
#        weightp: smart
#        bframes: 3
#        opts: "keyint=96:min-keyint=96:no-scenecut"
#        profile: high
#        level: 3.1
#      bitrate: 1200k
#      maxrate: 1200k
#      bufsize: 2400k
#    audio:
#      codec:
#        name: aac
#      channels: 5.1
#      bitrate: 196k

#
#  exp_xvid_x1_pal_gray_sd:
#    # Other options are inherited from `base`
#    extends:   base
#    passes: 1
#    format: mp4
#    video:
#      width:  -1  # 1024 # for 16:9
#      height: 576 # SD
#      codec:
#        name: xvid
#      bitrate: 1000k
#      maxrate: 1000k
#      bufsize: 2000k
#    audio:
#      codec:
#        name: mp3
#      channels: 5.1
#      bitrate: 196k
#

profile_screen:
  screen_hd:
    source:
      video:
        device: ":0.0"
    video:
      width: 1280
      height:  720
      bitrate: 2000k
      preset: veryfast
      codec:
        level: 3.1
        name : h264
        profile: high444
        weightp: smart
        bframes: 3
        opts: "keyint=96:min-keyint=96:no-scenecut"
    audio:
      channels: 5.1
      bitrate: 320k
      codec:
        name: aac
  screen_lw:
    # Other options are inherited from `screen_hd`
    extends: screen_hd
    video:
      width: 480
      height:  270
      bitrate: 250k
      codec:
        level: 3.0
    audio:
      channels: mono
      bitrate: 64k
