ffmpeg:
  bin: /usr/bin/ffmpeg
  threads: 0
  start: 00:00:00
  duration:  00:00:10
profile:
  tvzavr_h264p2:
    # you can mark profile as abstract
    # and it will be used only for inheritance.
    abstract: 1
    passes: 2
    video:
      preset: veryslow
      codec:
        name : h264
        weightp: 2
        bframes: 3
        opts: "keyint=96:min-keyint=96:no-scenecut"
    audio:
      codec:
        name: aac
  tvzavr_h264p2_hd:
    # Other options are inherited from `tvzavr_h264p2_base`
    extends: tvzavr_h264p2
    video:
      width: 1280
      height:  720
      bitrate: 2000k
      codec:
        profile: high
        level: 3.1
    audio:
      channels: 6 # 5.1
      bitrate: 320k
  tvzavr_h264p2_hi:
    # Other options are inherited from `tvzavr_h264p2_base`
    extends: tvzavr_h264p2
    video:
      width: 854
      height:  480
      bitrate: 1000k
      codec:
        profile: main
        level: 3.0
    audio:
      channels: 3 # stereo 3
      bitrate: 196k
  tvzavr_h264p2_nr:
    # Other options are inherited from `tvzavr_h264p2_base`
    extends: tvzavr_h264p2
    video:
      width: 640
      height:  360
      bitrate: 600k
      codec:
        profile: main
        level: 3.0
    audio:
      channels: 2 # stereo
      bitrate: 128k
  tvzavr_h264p2_lw:
    # Other options are inherited from `tvzavr_h264p2_base`
    extends: tvzavr_h264p2
    video:
      width: 480
      height:  270
      bitrate: 250k
      codec:
        profile: baseline
        level: 3.0
    audio:
      channels: 1 # mono
      bitrate: 64k



examples:
  profile_for_screen:
    screen_hd:
      video:
        width: 1280
        height:  720
        bitrate: 2000k
        preset: veryfast
        codec:
          level: 3.1
          name : h264
          profile: high444
          weightp: 2
          bframes: 3
          opts: "keyint=96:min-keyint=96:no-scenecut"
      audio:
        channels: 5.1
        bitrate: 320k
        codec:
          name: aac
    screen_lw:
      # Other options are inherited from `screen_hd`
      extends: screen_hd
      video:
        width: 480
        height:  270
        bitrate: 250k
        codec:
          level: 3.0
      audio:
        channels: mono
        bitrate: 64k
