self:
  compatibility:
    from: 0.1463347060

ffmpeg:
  bin: /usr/bin/ffmpeg
  threads: 0

profile:

  base:
    # you can mark profile as is_abstract
    # and it will be used only for inheritance.
    is_abstract: true
    output_dir_name: ./out
    source: /home/w495/Videos/IST/ist-x-2.mp4
    ignore:
      start: 00:00:00
      stop: 00:00:30
      duration:  00:00:30

  ## Semi-TVzavr's profile for HDTV devices.
  ## Check in the player on the https://www.tvzavr.ru/
  tvzavr_h264_x2_1080p_hd:
    # Other options are inherited from `base`
    extends: base
    passes: 2
    video:
      width:   -1  # 1920 # for 16:9
      height:  1080
      bitrate: 4000k
      codec:
        name : h264
        framerate: 25       #     Set framerate to 25.
        level: 4.2
        preset: veryslow
        profile: high
        weightp: smart
        bframes: 3
        opts:
          keyint: 96
          min_keyint: 96
          no_scenecut: true
        gop:
          closed: true      #       Closed GOP
          no_scenecut: true #       Disable scenecut detecting
        use_cabac: true     #     CABAC (default entropy encoder)
      progressive: true     # Progressive scan (no interlacing).
      pixel_format: yuv420p # Chroma subsampling: 4:2:0
    audio:
      codec:
        name: aac
      channels: mono     #   Channels: Stereo or Stereo + 5.1
      bitrate: 128k     #   Recommended for 5.1


#  ## Semi-TVzavr's profile for Desctop PAL-like Web Video.
#  ## Check in the player on the https://www.tvzavr.ru/
#  tvzavr_h264_x2_0720p_hd:
#    extends: tvzavr_h264_x2_1080p_hd
#    video:
#      codec:
#        level: 3.1
#      width:   -1  # 1280 # for 16:9
#      height:  720
#      level: 3.1
#      bitrate: 2000k
#
#  ## Semi-TVzavr's profile for Desctop PAL-like Web Video.
#  ## Check in the player on the https://www.tvzavr.ru/
#  tvzavr_h264_x2_0576p_hi:
#    extends: tvzavr_h264_x2_0720p_hd
#    video:
#      width:  -1  # 1024 # for 16:9
#      height: 576 # SD
#      bitrate: 1000k
#      codec:
#        profile: main
#        level: 3.0
#    audio:
#      channels: stereo
#      bitrate: 196k
#
#  ## Semi-TVzavr's profile for Desctop NTSC and VGA-like Web Video.
#  ## Check in the player on the https://www.tvzavr.ru/
#  tvzavr_h264_x2_0480p_hi:
#    extends: tvzavr_h264_x2_0576p_hi
#    video:
#      width:   -2 # 854 # for 16:9
#      height:  480
#
#  ## Semi-TVzavr's profile for tablets.
#  ## Check in the player on the https://www.tvzavr.ru/
#  tvzavr_h264_x2_0360p_nr:
#    extends: tvzavr_h264_x2_0480p_hi
#    video:
#      width:   -1 # 640 # for 16:9
#      height:  360
#      bitrate: 600k
#    audio:
#      channels: stereo
#      bitrate: 128k
#
#  ## Semi-TVzavr's profile for old mobile devices
#  ## Check in the player on the https://www.tvzavr.ru/.
#  tvzavr_h264_x2_0270p_lw:
#    extends: tvzavr_h264_x2_0360p_nr
#    video:
#      width:   -1 # 480 # for 16:9
#      height:  270
#      bitrate: 250k
#      codec:
#        profile: baseline
#    audio:
#      channels: mono
#      bitrate: 64k
#
#  ## Semi-TVzavr's casted profile for old mobile devices
#  tvzavr_h264_x2_0240p_lw:
#    extends: tvzavr_h264_x2_0270p_lw
#    video:
#      width:   -1
#      height:  240
#      bitrate: 200k
#
#  ## Semi-TVzavr's profile for small devices
#  tvzavr_h264_x2_0120p_lw:
#    extends: tvzavr_h264_x2_0240p_lw
#    video:
#      width:   -1
#      height:  120
#      bitrate: 100k
#    audio:
#      bitrate: 32k
